INSERT INTO public."Location"(
	"Location_ID", "Country", "Address", "City", "Province\State", "Postal\Zip")
	VALUES (DEFAULT, 'Canada', '49 Shearstown Rd', 'Bay Roberts', 'NL', 'A0A1G0'),
	(DEFAULT, 'Canada', '51 Dogwood Dr', 'Gander', 'NL', 'A4TF45'),
	(DEFAULT, 'Canada', '8 Merrymeeting Rd', 'St. Johns', 'NL', 'A1E4E1'),
	(DEFAULT, 'Canada', '69 Frigmont St', 'Edmonton', 'AB', 'T7X3Y3'),
	(DEFAULT, 'Canada', '78 Lincoln Rd', 'Grand Falls-Windsor', 'NL', 'A5G4F3'),
	(DEFAULT, 'Canada', '1405 Bloor St W', 'Toronto', 'ON', 'L0S1E6'),
	(DEFAULT, 'Canada', '2601 Broadway Ave', 'Saskatoon', 'SK', 'S7K8A5'),
	(DEFAULT, 'Romaina', '1820 Traian Mosoiu', 'Transylvania', 'RO', '077065'),
	(DEFAULT, 'Canada', '9085 Rue Hochelaga', 'Montréal', 'QC', 'H2S 1K6'),
	(DEFAULT, 'Canada', '458 W Broadway', 'Vancouver', 'BC', 'V6B 1B6'),
	(DEFAULT, 'Canada', '342 Freshwater Rd', 'St. Johns', 'NL', 'A1E6Y2'),
	(DEFAULT, 'Canada', '47 Harvey Rd', 'St. Johns', 'NL', 'A1E1T3'),
	(DEFAULT, 'Canada', '160 Water St', 'St. Johns', 'NL', 'A1E2S4'),
	(DEFAULT, 'Canada', '9 Bonaventure Ave', 'St. Johns', 'NL', 'A1E1E3'),
	(DEFAULT, 'Canada', '220 Water St', 'St. Johns', 'NL', 'A1E5U3'),
	(DEFAULT, 'Canada', '1 Military Rd', 'St. Johns', 'NL', 'A1E2K0'),
	(DEFAULT, 'Canada', '2381 Rue Beaubien Est', 'Montréal', 'QC', 'H2S1M8'),
	(DEFAULT, 'Canada', '7899 Templeton Station Rd', 'Richmond', 'BC', 'V2Y1A2'),
	(DEFAULT, 'Canada', 'St-Jean-sur-Richelieu', 'Montréal', 'QC', 'J7V 0H1'),
	(DEFAULT, 'Canada', '2673 Chemin Sainte-Foy', 'Sainte-Foy', 'QC', 'H3X 2J7'),
	(DEFAULT, 'Canada', '2121 Boulevard le Carrefour', 'Laval', 'QC', 'G1E0A4'),
	(DEFAULT, 'Canada', '91374 Alaska Hwy', 'Whitehorse', 'YT', 'Y0B1A0'),
	(DEFAULT, 'Canada', '227 Advance Bl', 'Brampton', 'ON', 'L7R4B6');