version: '3'
services:
  myapp-main:
    image: sdat_qap2:1.0.0
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/sdat_qap2?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}